server:
  port: 8080
spring:
  # Database properties
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
# SWAGGER
# To access Swagger UI, the default url is /swagger-ui.html
# In local environment, it's http://localhost:8090/swagger-ui.html
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
